# Generated by Django 5.2.4 on 2025-09-01 13:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achivements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='achievements/images/'),
        ),
    ]
