# Generated by Django 5.2.5 on 2025-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='photo',
            field=models.ImageField(default='abc', upload_to='winner_photos/'),
            preserve_default=False,
        ),
    ]
