# Generated by Django 5.2.4 on 2025-09-01 13:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0002_winner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sports_images/'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='winner_photos/'),
        ),
    ]
