# Generated by Django 5.2.4 on 2025-08-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject_images/')),
                ('subject_id', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('class_id', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('unit_id', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.subject')),
            ],
            options={
                'unique_together': {('subject', 'unit_id')},
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('syllabus_id', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='syllabus_images/')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='learning.section')),
            ],
            options={
                'unique_together': {('section', 'syllabus_id')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(default=1)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='syllabus_parts_images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='learning.syllabus')),
            ],
            options={
                'unique_together': {('syllabus', 'part_id')},
            },
        ),
    ]
