# Generated by Django 5.2.4 on 2025-08-20 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('vacancies', models.IntegerField(default=1)),
                ('qualification', models.CharField(max_length=200)),
                ('job_description_pdf', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('years_of_experience', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job')),
            ],
        ),
    ]
