# Generated by Django 5.2.4 on 2025-08-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description_pdf',
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
