# Generated by Django 5.2.4 on 2025-08-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teachersprofview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tittle', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='teachers/prof_pic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('college_or_uni', models.CharField(blank=True, max_length=150, null=True)),
                ('yearofpass', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('active', 'active'), ('retired', 'retired'), ('deceased', 'deceased')], default='active', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
