# Generated by Django 5.2.4 on 2025-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachersprofview_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersprofview',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/prof_pic/'),
        ),
    ]
