# Generated by Django 5.2.4 on 2025-08-26 18:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teachersprofview_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersprofview',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
