# Generated by Django 5.2.4 on 2025-08-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('organizer', models.CharField(choices=[('Administration', 'Administration'), ('Academic Department', 'Academic Department'), ('Arts Department', 'Arts Department'), ('Sports Department', 'Sports Department'), ('Science Department', 'Science Department'), ('Student Council', 'Student Council'), ('Parent Association', 'Parent Association'), ('Technology Club', 'Technology Club'), ('Cultural Club', 'Cultural Club'), ('Community Service Club', 'Community Service Club')], default='Administration', max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=50)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Administrative', 'Administrative'), ('Technology', 'Technology'), ('Arts', 'Arts'), ('Community', 'Community'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Celebration', 'Celebration')], default='Academic', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('title', 'description')},
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.event')),
            ],
        ),
    ]
