# Generated by Django 5.2.4 on 2025-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Administrative', 'Administrative'), ('Technology', 'Technology'), ('Arts', 'Arts'), ('Community Service', 'Community Service'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Celebration', 'Celebration')], default='Academic', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('Ongoing', 'Ongoing')], default='upcoming', max_length=50),
        ),
    ]
