# Generated by Django 5.2.4 on 2025-08-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_event_category_alter_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='winner_photos/')),
                ('student_class', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='programs.event')),
            ],
        ),
    ]
