# Generated by Django 5.2.5 on 2025-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aboutus", models.TextField()),
                ("schoolName", models.CharField(max_length=100)),
                ("schoolDescription", models.TextField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
