# Generated by Django 5.2.5 on 2025-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AboutUs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
