# Generated by Django 5.2.5 on 2025-08-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AboutUs", "0002_alter_aboutusmodel_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutUsModel",
        ),
    ]
