# Generated by Django 5.2.5 on 2025-08-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AboutUs", "0003_delete_aboutusmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
            ],
        ),
    ]
