# Generated by Django 5.2.5 on 2025-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AboutUs", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="AboutUs Images"),
        ),
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
