# Generated by Django 5.2.5 on 2025-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AboutUs", "0005_alter_aboutusmodel_image_alter_aboutusmodel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutusmodel",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
