# Generated by Django 5.2.4 on 2025-09-01 13:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0006_alter_aboutusmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='AboutUs Images'),
        ),
    ]
